/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_REQUIRED_H_
#define STATECHART_REQUIRED_H_

#include "./sc_types.h"
#include "Statechart.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This is a state machine uses time events which require access to a timing service. Thus the function prototypes:
- statechart_set_timer and
- statechart_unset_timer
are defined.
This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- statechart_iniciar_timer
- statechart_prender_LED1
- statechart_prender_LED2
- statechart_prender_LED3
- statechart_prender_LED4
- statechart_registrar_tiempo
- statechart_registrar_velocidad
- statechart_reiniciar_timer
- statechart_reiniciar_display
- statechart_mostrar_velocidad
- statechart_mostrar_tiempo_total
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- make sure that the execution time is as short as possible.
*/
extern void statechart_iniciar_timer( Statechart* handle);
extern void statechart_prender_LED1( Statechart* handle);
extern void statechart_prender_LED2( Statechart* handle);
extern void statechart_prender_LED3( Statechart* handle);
extern void statechart_prender_LED4( Statechart* handle);
extern void statechart_registrar_tiempo( Statechart* handle);
extern void statechart_registrar_velocidad( Statechart* handle);
extern void statechart_reiniciar_timer( Statechart* handle);
extern void statechart_reiniciar_display( Statechart* handle);
extern void statechart_mostrar_velocidad( Statechart* handle);
extern void statechart_mostrar_tiempo_total( Statechart* handle);




/*! 
This function has to set up timers for the time events that are required by the state machine.
It will be called for each time event that is relevant for a state when a state will be entered.
\param evid An unique identifier of the event.
\time_ms The time in milliseconds
\periodic Indicates the the time event must be raised periodically until the timer is unset 
*/
extern void statechart_set_timer(Statechart* handle, const sc_eventid evid, const sc_time time_ms, const sc_boolean periodic);

/*! 
This function has to unset timers for the time events that are required by the state machine.
It will be called for each time event that is relevant for a state when a state will be left.
\param evid An unique identifier of the event.
*/
extern void statechart_unset_timer(Statechart* handle, const sc_eventid evid);



#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_REQUIRED_H_ */
