/* Generated by itemis CREATE code generator. */


#include "../Inc/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_MEDICION(Statechart* handle);
static void enact_main_region_REPOSO(Statechart* handle);
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED3(Statechart* handle);
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED4(Statechart* handle);
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED1(Statechart* handle);
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED2(Statechart* handle);
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED3(Statechart* handle);
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED4(Statechart* handle);
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED1(Statechart* handle);
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED2(Statechart* handle);
static void enseq_main_region_MEDICION_default(Statechart* handle);
static void enseq_main_region_REPOSO_default(Statechart* handle);
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED3_default(Statechart* handle);
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED4_default(Statechart* handle);
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED1_default(Statechart* handle);
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED2_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_default(Statechart* handle);
static void exseq_main_region_MEDICION(Statechart* handle);
static void exseq_main_region_REPOSO(Statechart* handle);
static void exseq_main_region_DISPLAY_ENCENDIDO(Statechart* handle);
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED3(Statechart* handle);
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED4(Statechart* handle);
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED1(Statechart* handle);
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED2(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void exseq_main_region_DISPLAY_ENCENDIDO_r1(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);
static void react_main_region_DISPLAY_ENCENDIDO_r1__entry_Default(Statechart* handle);

/*! The reactions of state MEDICION. */
static sc_integer main_region_MEDICION_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state REPOSO. */
static sc_integer main_region_REPOSO_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state DISPLAY ENCENDIDO. */
static sc_integer main_region_DISPLAY_ENCENDIDO_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state LED3. */
static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED3_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state LED4. */
static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED4_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state LED1. */
static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED1_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state LED2. */
static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED2_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_ton(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);
static StatechartEventID statechart_get_timed_event_name(Statechart* handle, sc_eventid evid);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_set_cantidad_vueltas(handle, 0);
	statechart_set_total_vueltas(handle, 4);
	statechart_internal_set_ton(handle, 5);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_in_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void statechart_raise_time_event(Statechart* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(StatechartTimeEvents))
	{
		statechart_add_event_to_queue(&(handle->in_event_queue), statechart_get_timed_event_name(handle, evid));
		run_cycle(handle);
	}
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_MEDICION :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_MEDICION] == Statechart_main_region_MEDICION
			);
				break;
		case Statechart_main_region_REPOSO :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_REPOSO] == Statechart_main_region_REPOSO
			);
				break;
		case Statechart_main_region_DISPLAY_ENCENDIDO :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAY_ENCENDIDO] >= Statechart_main_region_DISPLAY_ENCENDIDO
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAY_ENCENDIDO] <= Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2);
				break;
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAY_ENCENDIDO_R1_LED3] == Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3
			);
				break;
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAY_ENCENDIDO_R1_LED4] == Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4
			);
				break;
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAY_ENCENDIDO_R1_LED1] == Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1
			);
				break;
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2 :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_DISPLAY_ENCENDIDO_R1_LED2] == Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.paso_el_auto_raised = bool_false;
	handle->ifaceBoton.reinicio_pressed_raised = bool_false;
	handle->ifaceBoton.velocidad_pressed_raised = bool_false;
	handle->ifaceBoton.tiempo_total_pressed_raised = bool_false;
	handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_tev0_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_MEDICION :
		{
			main_region_MEDICION_react(handle,-1);
			break;
		}
		case Statechart_main_region_REPOSO :
		{
			main_region_REPOSO_react(handle,-1);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3 :
		{
			main_region_DISPLAY_ENCENDIDO_r1_LED3_react(handle,-1);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4 :
		{
			main_region_DISPLAY_ENCENDIDO_r1_LED4_react(handle,-1);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1 :
		{
			main_region_DISPLAY_ENCENDIDO_r1_LED1_react(handle,-1);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2 :
		{
			main_region_DISPLAY_ENCENDIDO_r1_LED2_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			clear_in_events(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_paso_el_auto(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_paso_el_auto);
	run_cycle(handle);
}



sc_integer statechart_get_cantidad_vueltas(const Statechart* handle)
{
	return handle->iface.cantidad_vueltas;
}
void statechart_set_cantidad_vueltas(Statechart* handle, sc_integer value)
{
	handle->iface.cantidad_vueltas = value;
}
sc_integer statechart_get_total_vueltas(const Statechart* handle)
{
	return handle->iface.total_vueltas;
}
void statechart_set_total_vueltas(Statechart* handle, sc_integer value)
{
	handle->iface.total_vueltas = value;
}
void statechart_boton_raise_reinicio_pressed(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_boton_reinicio_pressed);
	run_cycle(handle);
}

void statechart_boton_raise_velocidad_pressed(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_boton_velocidad_pressed);
	run_cycle(handle);
}

void statechart_boton_raise_tiempo_total_pressed(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_boton_tiempo_total_pressed);
	run_cycle(handle);
}




static void statechart_internal_set_ton(Statechart* handle, sc_integer value)
{
	handle->internal.ton = value;
}


/* implementations of all internal functions */

static void enact_main_region_MEDICION(Statechart* handle)
{
	/* Entry action for state 'MEDICION'. */
	statechart_iniciar_timer(handle);
	handle->completed = bool_true;
}

/* Entry action for state 'REPOSO'. */
static void enact_main_region_REPOSO(Statechart* handle)
{
	/* Entry action for state 'REPOSO'. */
	statechart_set_cantidad_vueltas(handle, 0);
}

/* Entry action for state 'LED3'. */
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED3(Statechart* handle)
{
	/* Entry action for state 'LED3'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_tev0_raised) , ((sc_time) handle->internal.ton), bool_false);
	statechart_prender_LED3(handle);
}

/* Entry action for state 'LED4'. */
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED4(Statechart* handle)
{
	/* Entry action for state 'LED4'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_tev0_raised) , ((sc_time) handle->internal.ton), bool_false);
	statechart_prender_LED4(handle);
}

/* Entry action for state 'LED1'. */
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED1(Statechart* handle)
{
	/* Entry action for state 'LED1'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_tev0_raised) , ((sc_time) handle->internal.ton), bool_false);
	statechart_prender_LED1(handle);
}

/* Entry action for state 'LED2'. */
static void enact_main_region_DISPLAY_ENCENDIDO_r1_LED2(Statechart* handle)
{
	/* Entry action for state 'LED2'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_tev0_raised) , ((sc_time) handle->internal.ton), bool_false);
	statechart_prender_LED2(handle);
}

/* Exit action for state 'LED3'. */
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED3(Statechart* handle)
{
	/* Exit action for state 'LED3'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_tev0_raised) );		
}

/* Exit action for state 'LED4'. */
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED4(Statechart* handle)
{
	/* Exit action for state 'LED4'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_tev0_raised) );		
}

/* Exit action for state 'LED1'. */
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED1(Statechart* handle)
{
	/* Exit action for state 'LED1'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_tev0_raised) );		
}

/* Exit action for state 'LED2'. */
static void exact_main_region_DISPLAY_ENCENDIDO_r1_LED2(Statechart* handle)
{
	/* Exit action for state 'LED2'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_tev0_raised) );		
}

/* 'default' enter sequence for state MEDICION */
static void enseq_main_region_MEDICION_default(Statechart* handle)
{
	/* 'default' enter sequence for state MEDICION */
	enact_main_region_MEDICION(handle);
	handle->stateConfVector[0] = Statechart_main_region_MEDICION;
}

/* 'default' enter sequence for state REPOSO */
static void enseq_main_region_REPOSO_default(Statechart* handle)
{
	/* 'default' enter sequence for state REPOSO */
	enact_main_region_REPOSO(handle);
	handle->stateConfVector[0] = Statechart_main_region_REPOSO;
}

/* 'default' enter sequence for state LED3 */
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED3_default(Statechart* handle)
{
	/* 'default' enter sequence for state LED3 */
	enact_main_region_DISPLAY_ENCENDIDO_r1_LED3(handle);
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3;
}

/* 'default' enter sequence for state LED4 */
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED4_default(Statechart* handle)
{
	/* 'default' enter sequence for state LED4 */
	enact_main_region_DISPLAY_ENCENDIDO_r1_LED4(handle);
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4;
}

/* 'default' enter sequence for state LED1 */
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED1_default(Statechart* handle)
{
	/* 'default' enter sequence for state LED1 */
	enact_main_region_DISPLAY_ENCENDIDO_r1_LED1(handle);
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1;
}

/* 'default' enter sequence for state LED2 */
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_LED2_default(Statechart* handle)
{
	/* 'default' enter sequence for state LED2 */
	enact_main_region_DISPLAY_ENCENDIDO_r1_LED2(handle);
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_DISPLAY_ENCENDIDO_r1_default(Statechart* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_DISPLAY_ENCENDIDO_r1__entry_Default(handle);
}

/* Default exit sequence for state MEDICION */
static void exseq_main_region_MEDICION(Statechart* handle)
{
	/* Default exit sequence for state MEDICION */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state REPOSO */
static void exseq_main_region_REPOSO(Statechart* handle)
{
	/* Default exit sequence for state REPOSO */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state DISPLAY ENCENDIDO */
static void exseq_main_region_DISPLAY_ENCENDIDO(Statechart* handle)
{
	/* Default exit sequence for state DISPLAY ENCENDIDO */
	exseq_main_region_DISPLAY_ENCENDIDO_r1(handle);
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state LED3 */
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED3(Statechart* handle)
{
	/* Default exit sequence for state LED3 */
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO;
	exact_main_region_DISPLAY_ENCENDIDO_r1_LED3(handle);
}

/* Default exit sequence for state LED4 */
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED4(Statechart* handle)
{
	/* Default exit sequence for state LED4 */
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO;
	exact_main_region_DISPLAY_ENCENDIDO_r1_LED4(handle);
}

/* Default exit sequence for state LED1 */
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED1(Statechart* handle)
{
	/* Default exit sequence for state LED1 */
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO;
	exact_main_region_DISPLAY_ENCENDIDO_r1_LED1(handle);
}

/* Default exit sequence for state LED2 */
static void exseq_main_region_DISPLAY_ENCENDIDO_r1_LED2(Statechart* handle)
{
	/* Default exit sequence for state LED2 */
	handle->stateConfVector[0] = Statechart_main_region_DISPLAY_ENCENDIDO;
	exact_main_region_DISPLAY_ENCENDIDO_r1_LED2(handle);
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_MEDICION :
		{
			exseq_main_region_MEDICION(handle);
			break;
		}
		case Statechart_main_region_REPOSO :
		{
			exseq_main_region_REPOSO(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO :
		{
			exseq_main_region_DISPLAY_ENCENDIDO(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED3(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED4(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED1(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED2(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_DISPLAY_ENCENDIDO_r1(Statechart* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of Statechart.main_region.DISPLAY_ENCENDIDO.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED3(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED4(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED1(handle);
			break;
		}
		case Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2 :
		{
			exseq_main_region_DISPLAY_ENCENDIDO_r1_LED2(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_REPOSO_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_DISPLAY_ENCENDIDO_r1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_DISPLAY_ENCENDIDO_r1_LED1_default(handle);
}


static sc_integer main_region_MEDICION_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state MEDICION. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state MEDICION */
		handle->stateConfVector[0] = Statechart_last_state;
		/* 'default' enter sequence for state DISPLAY ENCENDIDO */
		enseq_main_region_DISPLAY_ENCENDIDO_r1_default(handle);
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}

static sc_integer main_region_REPOSO_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state REPOSO. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.paso_el_auto_raised == bool_true)
			{ 
				exseq_main_region_REPOSO(handle);
				enseq_main_region_MEDICION_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_DISPLAY_ENCENDIDO_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DISPLAY ENCENDIDO. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->ifaceBoton.reinicio_pressed_raised == bool_true)
			{ 
				exseq_main_region_DISPLAY_ENCENDIDO(handle);
				statechart_reiniciar_display(handle);
				statechart_reiniciar_timer(handle);
				enseq_main_region_REPOSO_default(handle);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			if (((handle->iface.paso_el_auto_raised) == bool_true) && (((handle->iface.cantidad_vueltas) == (handle->iface.total_vueltas)) == bool_true))
			{ 
				statechart_registrar_velocidad(handle);
				statechart_mostrar_velocidad(handle);
			} 
			if (((handle->iface.paso_el_auto_raised) == bool_true) && (((handle->iface.cantidad_vueltas) < (handle->iface.total_vueltas)) == bool_true))
			{ 
				statechart_registrar_tiempo(handle);
				handle->iface.cantidad_vueltas++;
			} 
			if (((handle->ifaceBoton.velocidad_pressed_raised) == bool_true) && (((handle->iface.cantidad_vueltas) >= (handle->iface.total_vueltas)) == bool_true))
			{ 
				statechart_mostrar_velocidad(handle);
			} 
			if (((handle->ifaceBoton.tiempo_total_pressed_raised) == bool_true) && (((handle->iface.cantidad_vueltas) >= (handle->iface.total_vueltas)) == bool_true))
			{ 
				statechart_mostrar_tiempo_total(handle);
			} 
			transitioned_after = transitioned_before;
		} 
	} return transitioned_after;
}

static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED3_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LED3. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_tev0_raised == bool_true)
			{ 
				exseq_main_region_DISPLAY_ENCENDIDO_r1_LED3(handle);
				handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_tev0_raised = bool_false;
				enseq_main_region_DISPLAY_ENCENDIDO_r1_LED4_default(handle);
				main_region_DISPLAY_ENCENDIDO_react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_DISPLAY_ENCENDIDO_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED4_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LED4. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_tev0_raised == bool_true)
			{ 
				exseq_main_region_DISPLAY_ENCENDIDO_r1_LED4(handle);
				handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_tev0_raised = bool_false;
				enseq_main_region_DISPLAY_ENCENDIDO_r1_LED1_default(handle);
				main_region_DISPLAY_ENCENDIDO_react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_DISPLAY_ENCENDIDO_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED1_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LED1. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_tev0_raised == bool_true)
			{ 
				exseq_main_region_DISPLAY_ENCENDIDO_r1_LED1(handle);
				handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_tev0_raised = bool_false;
				enseq_main_region_DISPLAY_ENCENDIDO_r1_LED2_default(handle);
				main_region_DISPLAY_ENCENDIDO_react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_DISPLAY_ENCENDIDO_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_DISPLAY_ENCENDIDO_r1_LED2_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LED2. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_tev0_raised == bool_true)
			{ 
				exseq_main_region_DISPLAY_ENCENDIDO_r1_LED2(handle);
				handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_tev0_raised = bool_false;
				enseq_main_region_DISPLAY_ENCENDIDO_r1_LED3_default(handle);
				main_region_DISPLAY_ENCENDIDO_react(handle,0);
				transitioned_after = 0;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_DISPLAY_ENCENDIDO_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_paso_el_auto:
		{
			handle->iface.paso_el_auto_raised = bool_true;
			return bool_true;
		}
		case Statechart_boton_reinicio_pressed:
		{
			handle->ifaceBoton.reinicio_pressed_raised = bool_true;
			return bool_true;
		}
		case Statechart_boton_velocidad_pressed:
		{
			handle->ifaceBoton.velocidad_pressed_raised = bool_true;
			return bool_true;
		}
		case Statechart_boton_tiempo_total_pressed:
		{
			handle->ifaceBoton.tiempo_total_pressed_raised = bool_true;
			return bool_true;
		}
		case Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_time_event_0:
		{
			handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_tev0_raised = bool_true;
			return bool_true;
		}
		case Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_time_event_0:
		{
			handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_tev0_raised = bool_true;
			return bool_true;
		}
		case Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_time_event_0:
		{
			handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_tev0_raised = bool_true;
			return bool_true;
		}
		case Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_time_event_0:
		{
			handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_tev0_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}

static StatechartEventID statechart_get_timed_event_name(Statechart* handle, sc_eventid evid)
{
	if(evid == &handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_tev0_raised) {
		return Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED3_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_tev0_raised) {
		return Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED4_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_tev0_raised) {
		return Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED1_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_tev0_raised) {
		return Statechart_Statechart_main_region_DISPLAY_ENCENDIDO_r1_LED2_time_event_0;
	}
	return Statechart_invalid_event;
}

